import Link from 'next/link';
import type { CyberProject } from '@/types';
import { EDR_DETECTIONS, EDR_IOCS, EDR_WORKFLOW } from '@/data/edrCaseStudy';

const SectionTitle = ({ number, children }: { number: string; children: React.ReactNode }) => <h2 className="case-title"><span>{number}</span>{children}</h2>;

export default function EdrCaseStudy({ project }: { project: CyberProject }) {
  return <main className="case-page relative px-6 py-14 md:py-20 max-w-6xl mx-auto">
    <Link href="/#cybersecurity-projects" className="text-link">← Back to Cybersecurity Projects</Link>
    <header id="overview" className="case-hero">
      <div className="flex flex-wrap gap-2 mb-6"><span className="status-badge status-completed">Completed</span><span className="status-badge">SOC Alert Triage</span><span className="status-badge status-progress">Hands-On EDR Training</span></div>
      <h1>Endpoint Detection &amp; Response Investigation</h1>
      <p className="case-supporting">TryHackMe — Introduction to EDR</p>
      <p className="case-lead">A practical SOC investigation of multiple endpoint detections using process lineage, command-line activity, file paths, network connections, indicators of compromise, MITRE ATT&amp;CK context, and threat intelligence.</p>
      <dl className="case-summary">{[['Role', project.role], ['Environment', project.platform], ['Scenario', project.scenarioTitle], ['Status', project.status], ['Primary Tool', project.siem]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      <div className="flex flex-wrap gap-3 mt-7"><a href="https://tryhackme.com/p/gabakoi21" target="_blank" rel="noopener noreferrer" className="button-secondary">View TryHackMe Profile ↗</a>{project.github && <a href={project.github} target="_blank" rel="noopener noreferrer" className="button-secondary">View GitHub Documentation ↗</a>}</div>
    </header>

    <nav className="case-toc" aria-label="Case study sections">{[['Overview','#overview'],['Objective','#objective'],['Workflow','#workflow'],['Detections','#detections'],['IOCs','#iocs'],['Findings','#findings'],['Skills','#skills'],['Lessons','#lessons']].map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav>

    <section className="case-block"><SectionTitle number="01">Scenario Overview</SectionTitle><p>I worked as a <strong>SOC analyst at the simulated TECH THM organization</strong> with access to an EDR console containing multiple medium- and high-severity detections. The dashboard provided detection summaries, endpoint and user context, process trees, command lines, executable metadata, registry and network activity, IOC tables, confidence scores, and threat-intelligence labels.</p><p>The exercise focused on understanding and interpreting the visibility supplied by the EDR. Alert acknowledgement, containment, quarantine, and other response actions were outside the assigned scope.</p></section>

    <section id="objective" className="case-block"><SectionTitle number="02">Investigation Objective</SectionTitle><p>My objective was to reconstruct what happened on each endpoint and answer precise triage questions with supporting evidence. This required identifying the tool used to download a payload, locating suspicious files, validating an exfiltration destination, and using threat intelligence to understand a detected utility.</p><div className="correlation-callout">Detection summary <b>+</b> Process chain <b>+</b> Endpoint evidence <b>+</b> Network activity <b>+</b> Threat intel <strong>→ Triage finding</strong></div></section>

    <section id="workflow" className="case-block"><SectionTitle number="03">EDR Triage Workflow</SectionTitle><div className="workflow-list">{EDR_WORKFLOW.map(([number,title,description]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>

    <section id="detections" className="case-block"><SectionTitle number="04">Detection Analysis</SectionTitle><div className="workflow-list">{EDR_DETECTIONS.map((detection, index) => <article key={detection.host}><span>0{index + 1}</span><div><div className="flex flex-wrap gap-2 mb-2"><span className="eyebrow">{detection.host}</span><span className="status-badge">{detection.severity}</span></div><h3>{detection.title}</h3><p>{detection.summary}</p><p className="case-subheading">Process / activity chain</p><div className="correlation-callout">{detection.chain}</div><p className="case-subheading">Evidence-backed findings</p><ul>{detection.findings.map(item => <li key={item}>• {item}</li>)}</ul><p className="method-note">MITRE / investigation context: {detection.mitre}</p></div></article>)}</div></section>

    <section id="iocs" className="case-block"><SectionTitle number="05">Indicators Correlated</SectionTitle><div className="report-grid">{EDR_IOCS.map(([type,value,notes]) => <article key={value}><span className="eyebrow">{type}</span><h3 className="mt-2" style={{overflowWrap:'anywhere'}}>{value}</h3><p>{notes}</p></article>)}</div></section>

    <section id="findings" className="case-block"><SectionTitle number="06">Key Investigation Findings</SectionTitle><div className="takeaway-grid"><article><h3>Payload download</h3><p>CMD.exe launched CURL.exe on DESKTOP-HR01, and the payload was saved as C:\Users\Public\install.exe.</p></article><article><h3>Suspicious executable</h3><p>syncsvc.exe was located at C:\Users\haris.khan\AppData\Local\Temp\syncsvc.exe on WIN-ENG-LAPTOP03.</p></article><article><h3>Exfiltration attempt</h3><p>The outbound upload targeted files-wetransfer.com and referenced dump_2025.dmp in the URL path.</p></article><article><h3>Threat-intel context</h3><p>UpdateAgent.exe on DESKTOP-DEV01 was labelled a known internal IT utility tool.</p></article></div></section>

    <section id="skills" className="case-block"><SectionTitle number="07">Skills Demonstrated</SectionTitle><div className="case-card-grid">{[['EDR operations',['Detection triage','Severity prioritization','Host and user scoping']],['Process analysis',['Parent-child relationships','Command-line review','Executable path analysis']],['Evidence correlation',['File, hash, domain and IP IOCs','Network activity','Threat-intelligence context']],['Documentation',['Evidence-backed findings','MITRE ATT&CK mapping','Clear analyst notes']]].map(([title,items]) => <article key={title as string}><h3>{title as string}</h3><ul>{(items as string[]).map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section id="lessons" className="case-block"><SectionTitle number="08">Lessons Learned</SectionTitle><div className="takeaway-grid"><article><h3>Follow the full process tree</h3><p>The process chain revealed how a trusted Office application led to CMD and cURL, exposing the actual download behavior.</p></article><article><h3>File location matters</h3><p>Public and Temp directories provided important context when evaluating downloaded or unfamiliar executables.</p></article><article><h3>Network evidence shows intent</h3><p>The complete destination URL made the attempted transfer and targeted dump file visible.</p></article><article><h3>Context prevents poor conclusions</h3><p>Threat intelligence showed that UpdateAgent.exe was an internal utility, demonstrating that an alert should not be judged by its name or severity alone.</p></article></div></section>

    <section className="training-context"><SectionTitle number="09">Training Context</SectionTitle><p>This case study documents hands-on work completed in the <strong>TryHackMe Introduction to EDR</strong> room within a controlled simulation. It demonstrates my investigation method and understanding of EDR telemetry; it is not presented as production SOC employment.</p><p>The indicators shown here belong to the training scenario. In a live environment, I would preserve evidence, document confidence and impact, follow the organization’s escalation procedure, and coordinate authorized containment and remediation.</p></section>
    <div className="flex flex-wrap justify-between gap-4 mt-10"><Link href="/#cybersecurity-projects" className="text-link">← Back to Cybersecurity Projects</Link><div className="flex flex-wrap gap-5"><a href="https://tryhackme.com/p/gabakoi21" target="_blank" rel="noopener noreferrer" className="text-link">View TryHackMe Profile ↗</a>{project.github && <a href={project.github} target="_blank" rel="noopener noreferrer" className="text-link">View GitHub Documentation ↗</a>}</div></div>
  </main>;
}
