import Link from 'next/link';
import type { CyberProject } from '@/types';

const SectionTitle = ({ number, children }: { number: string; children: React.ReactNode }) => (
  <h2 className="case-title"><span>{number}</span>{children}</h2>
);

const SPL_QUERIES = [
  { title: 'Validate the import', query: 'index=VPN_Logs\n| stats count', purpose: 'Confirm the total number of events stored in the new index.' },
  { title: 'Find a user', query: 'index=VPN_Logs\n| spath\n| search UserName="Maleena"\n| stats count', purpose: 'Count VPN events associated with the specified username.' },
  { title: 'Correlate an IP address', query: 'index=VPN_Logs\n| spath\n| search Source_ip="107.14.182.38"\n| stats values(UserName) as UserName count', purpose: 'Identify the username associated with a source IP and count matching events.' },
  { title: 'Exclude a country', query: 'index=VPN_Logs\n| spath\n| search Source_Country!="France"\n| stats count', purpose: 'Count events from every country except France.' },
  { title: 'Count activity from an IP', query: 'index=VPN_Logs\n| spath\n| search Source_ip="107.3.206.58"\n| stats count', purpose: 'Measure the number of VPN events associated with one source IP.' },
];

export default function SplunkBasicsCaseStudy({ project }: { project: CyberProject }) {
  return <main className="case-page relative px-6 py-14 md:py-20 max-w-6xl mx-auto">
    <Link href="/#cybersecurity-projects" className="text-link">← Back to Cybersecurity Projects</Link>
    <header id="overview" className="case-hero">
      <div className="flex flex-wrap gap-2 mb-6"><span className="status-badge status-completed">Completed</span><span className="status-badge">SIEM &amp; Log Analysis</span><span className="status-badge status-progress">Hands-On Splunk Training</span></div>
      <h1>Splunk: The Basics</h1>
      <p className="case-supporting">TryHackMe — Splunk: The Basics</p>
      <p className="case-lead">A practical introduction to Splunk architecture, log ingestion, JSON field extraction, and Search Processing Language through the investigation of VPN activity.</p>
      <dl className="case-summary">{[['Role', project.role], ['Environment', project.platform], ['Scenario', project.scenarioTitle], ['Status', project.status], ['SIEM', project.siem]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      <div className="flex flex-wrap gap-3 mt-7"><a href="https://tryhackme.com/p/gabakoi21" target="_blank" rel="noopener noreferrer" className="button-secondary">View TryHackMe Profile ↗</a><a href="https://docs.google.com/spreadsheets/d/1RATbhbF5mKPk_Pt0dHxwhIeHuqlBm17XUZdPtW3drUY/edit?gid=1326701418#gid=1326701418" target="_blank" rel="noopener noreferrer" className="button-secondary">View Splunk Cheat Sheet ↗</a></div>
    </header>

    <nav className="case-toc" aria-label="Case study sections">{[['Overview','#overview'],['Architecture','#architecture'],['Metadata','#metadata'],['Ingestion','#ingestion'],['Queries','#queries'],['Skills','#skills'],['Lessons','#lessons']].map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav>

    <section className="case-block"><SectionTitle number="01">Scenario Overview</SectionTitle><p>This room introduced <strong>Splunk Enterprise</strong> as a Security Information and Event Management platform used to collect, search, analyze, and visualize machine data. Organizations can centralize events from endpoints, applications, identity systems, network devices, firewalls, and business services to support monitoring and investigation.</p><p>The practical exercise used VPN logs to move from raw data ingestion to focused analysis. I uploaded a newline-delimited JSON file, stored it in a dedicated index, verified that each line became a separate event, and queried the resulting fields with SPL.</p></section>

    <section id="architecture" className="case-block"><SectionTitle number="02">Core Splunk Architecture</SectionTitle><div className="takeaway-grid"><article><h3>Forwarder</h3><p>A lightweight agent that collects data from endpoints or other sources and sends it to Splunk for processing.</p></article><article><h3>Indexer</h3><p>Processes incoming data, transforms it into searchable events, and stores it in indexes.</p></article><article><h3>Search Head</h3><p>Provides the interface where analysts run SPL searches, investigate events, build reports, and create dashboards.</p></article></div><div className="correlation-callout">Data source <b>→</b> Forwarder <b>→</b> Indexer <b>→</b> Search Head <strong>→ Analyst insight</strong></div></section>

    <section id="metadata" className="case-block"><SectionTitle number="03">Core Event Metadata</SectionTitle><div className="case-card-grid"><article><span>Storage</span><h3>index</h3><p>The logical data store that contains related events and defines the primary search scope.</p></article><article><span>Origin</span><h3>source</h3><p>The file, stream, or input from which an event originated.</p></article><article><span>Structure</span><h3>sourcetype</h3><p>Describes the data format and helps Splunk determine how events should be parsed.</p></article><article><span>Device</span><h3>host</h3><p>The endpoint, server, or device associated with the event.</p></article></div></section>

    <section id="ingestion" className="case-block"><SectionTitle number="04">VPN Log Ingestion</SectionTitle><p>I used Splunk’s <strong>Add Data → Upload</strong> workflow to import the supplied <strong>VPN_logs</strong> file. Because the file contained newline-delimited JSON, keeping the detected JSON source type ensured that every line was handled as an individual event.</p><div className="workflow-list">{[['01','Select Source','Choose Upload and select the local VPN_logs file.'],['02','Select Source Type','Keep the JSON source type detected by Splunk and confirm the event preview.'],['03','Input Settings','Create or select the VPN_Logs index and review the associated host value.'],['04','Review','Check the source, source type, host, and destination index before submission.'],['05','Complete','Finish the upload, open Search & Reporting, and set the time picker to All time.'],['06','Validate','Run a base search and compare the returned count with the imported dataset.']].map(([number,title,description]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>

    <section id="queries" className="case-block"><SectionTitle number="05">SPL Investigation Queries</SectionTitle><p><strong>SPL (Search Processing Language)</strong> uses a base search followed by pipe-delimited commands that progressively filter, transform, and summarize results. When JSON fields were not automatically visible, <code>| spath</code> extracted them from the event data.</p><div className="spl-query-grid">{SPL_QUERIES.map(item => <article key={item.title}><h3>{item.title}</h3><pre><code>{item.query}</code></pre><p>{item.purpose}</p></article>)}</div><p className="method-note">The exact challenge answer values are intentionally not reproduced here. The queries document the repeatable method used to obtain and validate each result in the lab.</p></section>

    <section id="skills" className="case-block"><SectionTitle number="06">Skills Demonstrated</SectionTitle><div className="case-card-grid">{[['Data onboarding',['Uploaded newline-delimited JSON','Selected the correct source type','Created a dedicated index']],['SPL fundamentals',['Scoped searches by index','Filtered structured fields','Used pipe-delimited commands']],['Field extraction',['Parsed JSON with spath','Validated usernames and IP fields','Handled exact field names']],['Event analysis',['Counted matching events','Correlated users with IPs','Excluded geographic values']]].map(([title,items]) => <article key={title as string}><h3>{title as string}</h3><ul>{(items as string[]).map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section id="lessons" className="case-block"><SectionTitle number="07">Key Lessons Learned</SectionTitle><div className="takeaway-grid"><article><h3>Parsing determines search quality</h3><p>Correct source-type selection and event boundaries are essential; poorly parsed data produces unreliable fields and counts.</p></article><article><h3>Time range matters</h3><p>Setting the time picker to All time prevents valid imported events from being hidden by the default search window.</p></article><article><h3>Validate before investigating</h3><p>A simple event count confirms that the dataset is present before more specific filters are applied.</p></article><article><h3>Field names are exact</h3><p>Queries must use the dataset’s precise field names and capitalization, such as UserName, Source_ip, and Source_Country.</p></article><article><h3>Pipes create readable analysis</h3><p>Breaking a search into extraction, filtering, and statistics stages makes the investigation easier to understand and verify.</p></article><article><h3>SIEM data needs context</h3><p>User, IP, country, host, and time information become more useful when they are correlated rather than reviewed in isolation.</p></article></div></section>

    <section className="training-context"><SectionTitle number="08">Training Context</SectionTitle><p>This case study documents hands-on learning completed in the <strong>TryHackMe Splunk: The Basics</strong> room. The work was performed in a controlled training environment and is not presented as production SOC employment.</p><p>The write-up focuses on concepts, configuration decisions, investigation methodology, and reusable SPL. Protected flags, credentials, and challenge answer values are intentionally excluded.</p></section>
    <div className="flex flex-wrap justify-between gap-4 mt-10"><Link href="/#cybersecurity-projects" className="text-link">← Back to Cybersecurity Projects</Link><div className="flex flex-wrap gap-5"><a href="https://tryhackme.com/p/gabakoi21" target="_blank" rel="noopener noreferrer" className="text-link">View TryHackMe Profile ↗</a><a href="https://docs.google.com/spreadsheets/d/1RATbhbF5mKPk_Pt0dHxwhIeHuqlBm17XUZdPtW3drUY/edit?gid=1326701418#gid=1326701418" target="_blank" rel="noopener noreferrer" className="text-link">Splunk Cheat Sheet ↗</a></div></div>
  </main>;
}
